<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByName($recherche)
    {
        $qb = $this->createQueryBuilder('u');

        return $qb
            ->where('u.username like :search')
            ->setParameter('search', $recherche.'%')
            ->getQuery()
            ->getResult();
    }
}
